// `pnpm harness catalogue` (build plan §5b item 8a, design 08 §9): renders every process template in
// `loadContent().templates` as words -- trigger, preconditions, options and outcomes with odds, effects and
// report line -- so the owner reviews the catalogue, not the code. Pure string-building over `Content`; no I/O
// here (the CLI writes the file and prints the path).

import type { CmpOp, Content, DecisionOption, Effect, Outcome, Predicate, ProcessTemplate, ReportSpec } from "@borgata/sim";

const HEADER = "Generated by `pnpm harness catalogue`; do not edit.";

// ---------------------------------------------------------------------------------------------------------------
// Predicate DSL -> words (engine/types.ts's `Predicate` union, design 04 §1). One phrase per shape; an unknown
// shape (a future predicate kind the catalogue has not been taught) falls back to its JSON, per the task brief.
// ---------------------------------------------------------------------------------------------------------------

const OP_WORD: Record<CmpOp, string> = { lt: "<", lte: "<=", gt: ">", gte: ">=", eq: "=", ne: "!=" };

function rangeSuffix(gte: number | undefined, lte: number | undefined): string {
  if (gte !== undefined && lte !== undefined) return ` between ${gte} and ${lte}`;
  if (gte !== undefined) return ` >= ${gte}`;
  if (lte !== undefined) return ` <= ${lte}`;
  return "";
}

export function renderPredicate(p: Predicate): string {
  if ("all" in p) return `all of: ${p.all.map(renderPredicate).join("; ")}`;
  if ("any" in p) return `any of: ${p.any.map(renderPredicate).join("; ")}`;
  if ("not" in p) return `not (${renderPredicate(p.not)})`;
  if ("cmp" in p) return `${p.cmp.role}.${p.cmp.path} ${OP_WORD[p.cmp.op]} ${p.cmp.value}`;
  if ("band" in p) return `${p.band.role}'s attention band${rangeSuffix(p.band.gte, p.band.lte)}`;
  if ("heat" in p) return `${p.heat.role}'s town heat${rangeSuffix(p.heat.gte, p.heat.lte)}`;
  if ("has" in p) {
    const h = p.has;
    if (h.trait !== undefined) return `${h.role} has trait "${h.trait}"`;
    if (h.tool !== undefined) return `${h.role} has tool "${h.tool}"`;
    if (h.memoryTag !== undefined) return `${h.role} has memory tag "${h.memoryTag}"`;
    return `${h.role} has (unspecified)`;
  }
  if ("status" in p) return `${p.status.role} status is ${Array.isArray(p.status.is) ? p.status.is.join(" or ") : p.status.is}`;
  if ("rank" in p) return `${p.rank.role} rank in [${p.rank.in.join(", ")}]`;
  if ("alive" in p) return `${p.alive.role} is alive`;
  if ("playerControlled" in p) return `${p.playerControlled.role} is ${p.playerControlled.is ? "" : "not "}player-controlled`;
  if ("recent" in p) {
    const r = p.recent;
    return `a ${r.factKind} fact${r.role ? ` involving ${r.role}` : ""} happened within ${r.withinTurns} turn${r.withinTurns === 1 ? "" : "s"}`;
  }
  if ("flag" in p) return `crisis flag "${p.flag.name}" is ${p.flag.active ? "active" : "inactive"}`;
  if ("activeTemplate" in p) {
    const a = p.activeTemplate;
    return `an active "${a.templateId}" instance${a.role ? ` bound to ${a.role}` : ""} ${a.exists ? "exists" : "does not exist"}`;
  }
  if ("sameEntity" in p) return `${p.sameEntity.a} and ${p.sameEntity.b} are ${p.sameEntity.is ? "" : "not "}the same entity`;
  if ("bound" in p) return `${p.bound.role} is ${p.bound.is ? "" : "not "}bound`;
  if ("cmpRoles" in p) return `${p.cmpRoles.a}.${p.cmpRoles.pathA} ${OP_WORD[p.cmpRoles.op]} ${p.cmpRoles.b}.${p.cmpRoles.pathB}`;
  if ("sameFamily" in p) return `${p.sameFamily.a} and ${p.sameFamily.b} are ${p.sameFamily.is ? "" : "not "}in the same family`;
  if ("decided" in p) return `the chosen option is "${p.decided.optionId}"`;
  if ("fn" in p) {
    const args = p.fn.args ? ` (${Object.entries(p.fn.args).map(([k, v]) => `${k}=${String(v)}`).join(", ")})` : "";
    return `passes check "${p.fn.name}"${args}`;
  }
  return `unknown predicate: ${JSON.stringify(p)}`;
}

// ---------------------------------------------------------------------------------------------------------------
// Effects -> words (engine/types.ts's `Effect` union). `RefValue`s (design 04 §1 header) are role references
// ("$role", "$role.account", ...), literals, `$expr` scale expressions or `$turnPlus` offsets.
// ---------------------------------------------------------------------------------------------------------------

/** A nested field pulled off a RefValue that is itself a plain object (e.g. an EvidenceAdd's `item`, a
 * MemoryAdd's `memory`, a LoanOpen's `loan`): those are never role references themselves, only their leaves are. */
function field(v: unknown, key: string): unknown {
  return v && typeof v === "object" ? (v as Record<string, unknown>)[key] : undefined;
}

function fmtRef(v: unknown): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean" || typeof v === "number") return String(v);
  if (typeof v === "string") {
    if (!v.startsWith("$")) return v;
    if (v === "$turn") return "current turn";
    if (v === "$instance") return "this instance";
    if (v === "$template") return "this template";
    if (v === "$chainRef") return "the cause chain";
    if (v.startsWith("$mint:")) return "a newly minted id";
    const bare = v.slice(1);
    const dot = bare.indexOf(".");
    return dot === -1 ? bare : bare.slice(0, dot);
  }
  if (Array.isArray(v)) return v.map(fmtRef).join(", ");
  if (typeof v === "object") {
    if ("$expr" in v) {
      const e = v as { $expr: { role: string; path: string; mul?: number; add?: number } };
      const parts = [`${e.$expr.role}.${e.$expr.path}`];
      if (e.$expr.mul !== undefined && e.$expr.mul !== 1) parts.push(`x${e.$expr.mul}`);
      if (e.$expr.add !== undefined && e.$expr.add !== 0) parts.push(`${e.$expr.add >= 0 ? "+" : ""}${e.$expr.add}`);
      return `scaled(${parts.join(" ")})`;
    }
    if ("$turnPlus" in v) return `turn+${(v as { $turnPlus: number }).$turnPlus}`;
    return Object.entries(v as Record<string, unknown>)
      .map(([k, vv]) => `${k}=${fmtRef(vv)}`)
      .join(", ");
  }
  return JSON.stringify(v);
}

function signedRef(v: unknown): string {
  if (typeof v === "number") return v >= 0 ? `+${v}` : `${v}`;
  return fmtRef(v);
}

/** One phrase per fact kind actually used by content today, plus a readable generic fallback for the rest of
 * the fact catalogue (facts.ts) so a future content addition never regresses to raw JSON. */
function renderFactEffect(e: Extract<Effect, { fact: string }>): string {
  const f = e.fact;
  const get = (k: string): unknown => (e as unknown as Record<string, unknown>)[k];
  switch (f) {
    case "FavorDelta":
      return `FavorDelta ${fmtRef(get("from"))}→${fmtRef(get("to"))} ${signedRef(get("delta"))}`;
    case "MoneyMint":
      return `MoneyMint ${fmtRef(get("to"))} ${signedRef(get("amount"))} ${fmtRef(get("money"))} (${fmtRef(get("source"))})`;
    case "MoneyMove":
      return `MoneyMove ${fmtRef(get("amount"))} ${fmtRef(get("money"))} ${fmtRef(get("from"))}→${fmtRef(get("to"))}`;
    case "MoneyDestroy":
      return `MoneyDestroy ${fmtRef(get("from"))} ${fmtRef(get("amount"))} ${fmtRef(get("money"))} (${fmtRef(get("sink"))})`;
    case "Launder":
      return `Launder ${fmtRef(get("account"))} ${fmtRef(get("amount"))} (fee ${fmtRef(get("feePermille"))}‰)`;
    case "LoyaltyDelta":
      return `LoyaltyDelta ${fmtRef(get("characterId"))} ${signedRef(get("delta"))}`;
    case "RecordDelta": {
      const setField = get("set");
      return `RecordDelta ${fmtRef(get("characterId"))} ${fmtRef(get("field"))} ${setField ? `= ${fmtRef(get("delta"))}` : signedRef(get("delta"))}`;
    }
    case "EvidenceAdd": {
      const item = get("item");
      return `EvidenceAdd ${fmtRef(get("characterId"))} +${fmtRef(field(item, "weight"))} (${fmtRef(field(item, "source"))})`;
    }
    case "EvidenceRemove":
      return `EvidenceRemove ${fmtRef(get("characterId"))} crime ${fmtRef(get("crimeRef"))}`;
    case "StatusChange": {
      const until = get("untilTurn");
      return `StatusChange ${fmtRef(get("characterId"))} -> ${fmtRef(get("status"))}${until !== undefined ? ` until ${fmtRef(until)}` : ""}`;
    }
    case "RankChange":
      return `RankChange ${fmtRef(get("characterId"))} -> ${fmtRef(get("rank"))}`;
    case "SuperiorSet":
      return `SuperiorSet ${fmtRef(get("characterId"))} -> ${fmtRef(get("superiorId"))}`;
    case "ShareRuleSet": {
      const rule = get("rule");
      return `ShareRuleSet ${fmtRef(get("superiorId"))}→${fmtRef(get("subordinateId"))} ${fmtRef(field(rule, "percent"))}‰ + ${fmtRef(field(rule, "fixedPerTurn"))} kL`;
    }
    case "CooperationSet":
      return `CooperationSet ${fmtRef(get("characterId"))}`;
    case "CharacterCreate":
      return `CharacterCreate "${fmtRef(get("name"))}" (${fmtRef(get("rank"))}), superior ${fmtRef(get("superiorId"))}`;
    case "MemoryAdd": {
      const m = get("memory");
      const about = field(m, "aboutId");
      return `MemoryAdd ${fmtRef(get("characterId"))} "${fmtRef(field(m, "tag"))}"${about !== undefined ? ` about ${fmtRef(about)}` : ""} (+${fmtRef(field(m, "weight"))})`;
    }
    case "HeatDelta":
      return `HeatDelta ${fmtRef(get("townId"))} ${signedRef(get("delta"))}`;
    case "AttentionDelta":
      return `AttentionDelta ${fmtRef(get("familyId"))} ${signedRef(get("delta"))}`;
    case "BandChange":
      return `BandChange ${fmtRef(get("familyId"))} ${fmtRef(get("from"))} -> ${fmtRef(get("to"))}`;
    case "ToolUnlock":
      return `ToolUnlock ${fmtRef(get("familyId"))} ${fmtRef(get("tool"))}`;
    case "ComplianceDelta":
      return `ComplianceDelta ${fmtRef(get("businessId"))} ${signedRef(get("delta"))}`;
    case "FearDelta":
      return `FearDelta ${fmtRef(get("businessId"))} ${signedRef(get("delta"))}`;
    case "RefusalStage":
      return `RefusalStage ${fmtRef(get("businessId"))} -> ${fmtRef(get("stage"))}`;
    case "SentimentDelta":
      return `SentimentDelta ${fmtRef(get("townId"))} ${signedRef(get("delta"))}`;
    case "PettyCrimeDelta":
      return `PettyCrimeDelta ${fmtRef(get("townId"))} ${signedRef(get("delta"))}`;
    case "CollectionMissed":
      return `CollectionMissed ${fmtRef(get("businessId"))} by ${fmtRef(get("collectorId"))}`;
    case "ClaimSet": {
      const subject = get("subject");
      return `ClaimSet ${fmtRef(field(subject, "kind"))} ${fmtRef(field(subject, "id"))} -> holder ${fmtRef(get("holderId"))}`;
    }
    case "ClaimTransfer":
      return `ClaimTransfer -> ${fmtRef(get("toHolderId"))}`;
    case "ClaimRelease":
      return `ClaimRelease`;
    case "CrewMemberAdd":
      return `CrewMemberAdd ${fmtRef(get("characterId"))} -> crew ${fmtRef(get("crewId"))}`;
    case "CrewMemberRemove":
      return `CrewMemberRemove ${fmtRef(get("characterId"))} from crew ${fmtRef(get("crewId"))}`;
    case "CrewChiefSet":
      return `CrewChiefSet crew ${fmtRef(get("crewId"))} -> ${fmtRef(get("chiefId"))}`;
    case "BlockAssign":
      return `BlockAssign block ${fmtRef(get("blockId"))} -> crew ${fmtRef(get("crewId"))}`;
    case "LoanOpen": {
      const loan = get("loan");
      const borrower = field(loan, "borrower");
      return `LoanOpen ${fmtRef(field(loan, "principal"))} kL to ${fmtRef(field(borrower, "kind"))} ${fmtRef(field(borrower, "id"))} at ${fmtRef(field(loan, "points"))}‰`;
    }
    case "LoanPayment":
      return `LoanPayment ${fmtRef(get("lenderId"))} ${fmtRef(get("amount"))} kL ${get("paid") ? "paid" : "missed"}`;
    case "LoanDefault":
      return `LoanDefault loan ${fmtRef(get("loanId"))}`;
    case "WeightSet":
      return `WeightSet ${fmtRef(get("characterId"))} = ${fmtRef(get("value"))}`;
    case "UiLayerUnlock":
      return `UiLayerUnlock ${fmtRef(get("layer"))}`;
    case "PermissionAsked":
      return `PermissionAsked ${fmtRef(get("characterId"))} ${fmtRef(get("what"))}`;
    case "ReportNote":
      return `ReportNote "${fmtRef(get("text"))}"`;
    case "RequestPush":
      return `RequestPush`;
    case "RequestResolve":
      return `RequestResolve`;
    case "RequestDefer":
      return `RequestDefer`;
    case "CrisisFlagSet":
      return `CrisisFlagSet ${fmtRef(get("flag"))} ${get("active") ? "on" : "off"} ttl ${fmtRef(get("ttl"))}`;
    case "TurnLengthSet":
      return `TurnLengthSet ${fmtRef(get("weeks"))} week(s)`;
    case "ChainCreate":
    case "ChainSlotFill":
    case "ChainSlotVacate":
    case "ChainRemove":
    case "ProcessSpawn":
    case "ProcessProgress":
    case "ProcessAwaitDecision":
    case "ProcessDecide":
    case "ProcessResolve":
    case "ProcessCancel":
    case "ScheduleAdd":
    case "ScheduleRemove":
      return `${f} (engine-internal)`;
    default:
      return `unknown fact effect: ${JSON.stringify(e)}`;
  }
}

export function renderEffect(e: Effect): string {
  if ("fact" in e) return renderFactEffect(e);
  if ("schedule" in e) {
    const s = e.schedule;
    const delay = typeof s.delay === "number" ? `${s.delay}` : `${s.delay.min}-${s.delay.max}`;
    const pct = s.probability !== undefined ? ` (${(s.probability / 100).toFixed(0)}%)` : "";
    return `schedule ${s.templateId} in ${delay}${pct}`;
  }
  if ("cancel" in e) return `cancel ${e.cancel.templateId}${e.cancel.boundTo ? ` bound to ${e.cancel.boundTo}` : ""} (${e.cancel.reason})`;
  if ("crisis" in e) return `crisis flag "${e.crisis.flag}" ${e.crisis.active ? "on" : "off"} for ${e.crisis.ttl} turns`;
  if ("request" in e) return `request: "${e.request.text}"`;
  if ("each" in e) {
    const ea = e.each;
    return `for each "${ea.as}" (${ea.relation} of ${ea.from}): ${ea.effects.map(renderEffect).join("; ")}`;
  }
  return `unknown effect: ${JSON.stringify(e)}`;
}

function renderEffects(effects: readonly Effect[]): string {
  return effects.length === 0 ? "no effects" : effects.map(renderEffect).join("; ");
}

// ---------------------------------------------------------------------------------------------------------------
// Spawn trigger -> words (engine/types.ts's `SpawnRule`).
// ---------------------------------------------------------------------------------------------------------------

export function renderSpawnTrigger(t: ProcessTemplate): string {
  const s = t.spawn;
  if (!s) return "scheduled only (no direct spawn rule; created by another template's `schedule` effect)";
  if (s.spawnFrom) {
    const sf = s.spawnFrom;
    const matchStr = sf.match ? ` matching {${Object.entries(sf.match).map(([k, v]) => `${k}: ${JSON.stringify(v)}`).join(", ")}}` : "";
    const bindStr = sf.role2 ? `${sf.role} from ${sf.field}, ${sf.role2} from ${sf.field2}` : `${sf.role} from ${sf.field}`;
    const within = sf.withinTurns ?? 1;
    return `reacts to ${sf.factKind}${matchStr} (binds ${bindStr}, within ${within} turn${within === 1 ? "" : "s"})`;
  }
  const cap = s.maxActivePerScope !== undefined ? `, max ${s.maxActivePerScope} active per ${s.per}` : "";
  return `per ${s.per}, weight ${s.weight} per ten thousand${cap}`;
}

// ---------------------------------------------------------------------------------------------------------------
// Outcomes: which ones belong to an option, and their relative odds (design 04 §1's `Outcome.weight`, default 1).
// ---------------------------------------------------------------------------------------------------------------

function matchesDecided(when: readonly Predicate[] | undefined, optionId: string): boolean {
  return !!when?.some((w) => "decided" in w && w.decided.optionId === optionId);
}

function anyOutcomeIsDecided(resolve: readonly Outcome[]): boolean {
  return resolve.some((o) => (o.when ?? []).some((w) => "decided" in w));
}

/** The outcomes gated to this option by a `decided` predicate, or every outcome when none of the template's
 * outcomes are gated by `decided` at all (task brief: "or all outcomes when none do"). */
export function outcomesForOption(resolve: readonly Outcome[], optionId: string): readonly Outcome[] {
  const matches = resolve.filter((o) => matchesDecided(o.when, optionId));
  if (matches.length > 0) return matches;
  return anyOutcomeIsDecided(resolve) ? [] : resolve;
}

export function oddsPercentages(outcomes: readonly Outcome[]): Map<string, number> {
  const total = outcomes.reduce((sum, o) => sum + (o.weight ?? 1), 0) || 1;
  const map = new Map<string, number>();
  for (const o of outcomes) map.set(o.id, Math.round(((o.weight ?? 1) / total) * 100));
  return map;
}

/** sponsor/sign/newspaper/lawyer, first present (task brief's stated priority). */
export function reportLineOf(r: ReportSpec | undefined): string | undefined {
  return r?.sponsor ?? r?.sign ?? r?.newspaper ?? r?.lawyer;
}

function renderOutcomeLine(out: Outcome, pct: Map<string, number>): string {
  const report = reportLineOf(out.report);
  return `\`${out.id}\` (${pct.get(out.id) ?? 0}%): ${renderEffects(out.effects)}${report ? ` — report: "${report}"` : ""}`;
}

// ---------------------------------------------------------------------------------------------------------------
// Grouping: one heading per tag family, in the file order `loadContent().templates` already preserves (the
// six `packages/content/src/templates/*.ts` files concatenate in `templates/index.ts`'s `ALL_TEMPLATES` order:
// state, civil, dispute, associate-week, associate-people, soldier). `codexId` names the source file directly
// for every file except associate-people.ts (no codexId there); its ids all start with "assoc." like its
// associate-week.ts sibling, so the id prefix is the fallback, also used for any future template with no codexId.
// ---------------------------------------------------------------------------------------------------------------

const FAMILY_BY_CODEX: Record<string, string> = {
  "associate-week": "Associate",
  "soldier-opening": "Soldier",
  "state-response": "State",
  "escalation-ladder": "Civil",
  "dispute-claim": "Dispute",
  // Design 12 (obligations, the treasury, lifestyle): ids are "oblig.*"/"family.*"/"lifestyle.*", none of
  // which is a recognized id prefix below; grouped under Civil, the same bucket "escalation-ladder" (also
  // outside the id-prefix scheme) already uses for a domain that does not map onto one of the other four.
  "obligations-treasury": "Civil",
  war: "Dispute",
  district: "Dispute",
  "dispute-stall-crew": "Dispute",
  "dispute-district-sitdown": "Dispute",
};

export function familyOf(t: ProcessTemplate): string {
  if (t.codexId && FAMILY_BY_CODEX[t.codexId]) return FAMILY_BY_CODEX[t.codexId]!;
  if (t.id.startsWith("assoc.")) return "Associate";
  if (t.id.startsWith("soldier.") || t.id.startsWith("chief.")) return "Soldier";
  if (t.id.startsWith("state.")) return "State";
  if (t.id.startsWith("dispute.")) return "Dispute";
  if (t.id.startsWith("civil.") || t.id.startsWith("family.")) return "Civil";
  return "Other";
}

function renderDecisionOption(t: ProcessTemplate, o: DecisionOption): string[] {
  const lines: string[] = [];
  const outcomes = outcomesForOption(t.resolve, o.id);
  const pct = oddsPercentages(outcomes);
  lines.push(`- \`${o.id}\` — ${o.label}${o.hint ? `: ${o.hint}` : ""}`);
  lines.push(`  - option effects: ${renderEffects(o.effects)}`);
  if (outcomes.length === 0) lines.push(`  - (no outcome in \`resolve\` is gated to this option)`);
  else for (const out of outcomes) lines.push(`  - ${renderOutcomeLine(out, pct)}`);
  return lines;
}

function renderTemplateSection(t: ProcessTemplate): string[] {
  const lines: string[] = [];
  lines.push(`### \`${t.id}\` (lane: ${t.lane}, kind: ${t.kind}, scope: ${t.scope})`);
  lines.push("");
  lines.push(`Trigger: ${renderSpawnTrigger(t)}`);
  lines.push("");
  lines.push("Preconditions:");
  if (t.preconditions.length === 0) lines.push("- (none)");
  else for (const p of t.preconditions) lines.push(`- ${renderPredicate(p)}`);
  lines.push("");

  if (t.decision) {
    // A priority list (design 04 hotspot 5) is rendered as its fallback order: first role bound to a
    // player-controlled character decides, else the last (the NPC default) -- see resolveDeciderRoleName.
    const roleDisplay = Array.isArray(t.decision.role) ? t.decision.role.join(" > ") : t.decision.role;
    lines.push(`Decision (role \`${roleDisplay}\`): ${t.decision.prompt}`);
    lines.push("");
    lines.push("| Option | Label | Hint |");
    lines.push("|---|---|---|");
    for (const o of t.decision.options) lines.push(`| \`${o.id}\` | ${o.label} | ${o.hint ?? "(none)"} |`);
    lines.push("");
    lines.push(`Outcomes by option (aiDefault \`${t.decision.aiDefault}\`, timeout ${t.decision.timeoutTurns} turn(s) -> \`${t.decision.timeoutOption}\`):`);
    lines.push("");
    const shown = new Set<string>();
    for (const o of t.decision.options) {
      for (const out of outcomesForOption(t.resolve, o.id)) shown.add(out.id);
      lines.push(...renderDecisionOption(t, o));
    }
    // Outcomes not gated to any specific option (e.g. a shared "otherwise" branch, disputes.ts's own `settled`):
    // `outcomesForOption` only returns them as every option's fallback when NO outcome is `decided`-gated at all,
    // so when some outcomes are gated and this one is not, it would otherwise never appear anywhere.
    const leftover = t.resolve.filter((out) => !shown.has(out.id));
    if (leftover.length > 0) {
      const pct = oddsPercentages(t.resolve);
      lines.push("General outcomes (not gated to a specific option):");
      for (const out of leftover) lines.push(`- ${renderOutcomeLine(out, pct)}`);
    }
  } else {
    lines.push("Outcomes:");
    const pct = oddsPercentages(t.resolve);
    for (const out of t.resolve) lines.push(`- ${renderOutcomeLine(out, pct)}`);
  }
  lines.push("");
  return lines;
}

/** Build the whole catalogue as Markdown text (task brief: "docs/catalogue.md"). Deterministic: same content,
 * same text, so the checked-in copy only changes when a template does. */
export function buildCatalogue(content: Content): string {
  const lines: string[] = [];
  lines.push(HEADER);
  lines.push("");
  lines.push("# Borgata process template catalogue");
  lines.push("");
  lines.push(`Content version \`${content.version}\`, ${content.templates.length} templates.`);
  lines.push("");

  let lastFamily: string | null = null;
  for (const t of content.templates) {
    const fam = familyOf(t);
    if (fam !== lastFamily) {
      lines.push(`## ${fam}`);
      lines.push("");
      lastFamily = fam;
    }
    lines.push(...renderTemplateSection(t));
  }

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}
