// Tests for `pnpm harness catalogue` (build plan §5b item 8a, design 08 §9): the catalogue is reviewed by the
// owner, not the code, so what matters is that every template's id, every decision option's id and every
// option's hint actually appear in the generated text -- if one goes missing, the owner is reviewing stale content.

import { describe, expect, it } from "vitest";
import { loadContent } from "@borgata/content";
import { buildCatalogue, familyOf, outcomesForOption, renderEffect, renderPredicate } from "./catalogue.js";

const content = loadContent();
const catalogue = buildCatalogue(content);

describe("buildCatalogue", () => {
  it("starts with the do-not-edit header", () => {
    expect(catalogue.startsWith("Generated by `pnpm harness catalogue`; do not edit.")).toBe(true);
  });

  it("contains every template id", () => {
    for (const t of content.templates) {
      expect(catalogue.includes(`\`${t.id}\``)).toBe(true);
    }
  });

  it("contains every decision option id and its hint, for every decision template", () => {
    for (const t of content.templates) {
      if (!t.decision) continue;
      for (const o of t.decision.options) {
        expect(catalogue.includes(`\`${o.id}\``)).toBe(true);
        if (o.hint) expect(catalogue.includes(o.hint)).toBe(true);
      }
    }
  });

  it("contains every outcome id", () => {
    for (const t of content.templates) {
      for (const o of t.resolve) {
        expect(catalogue.includes(`\`${o.id}\``)).toBe(true);
      }
    }
  });

  it("groups templates into exactly the five tag families the task brief names", () => {
    const headings = [...catalogue.matchAll(/^## (.+)$/gm)].map((m) => m[1]);
    expect(new Set(headings)).toEqual(new Set(["Associate", "Soldier", "State", "Civil", "Dispute"]));
  });

  it("is deterministic: building it twice from the same content gives the same text", () => {
    expect(buildCatalogue(content)).toBe(catalogue);
  });
});

describe("familyOf", () => {
  it("classifies every real template into one of the five families (no 'Other')", () => {
    for (const t of content.templates) expect(familyOf(t)).not.toBe("Other");
  });
});

describe("renderPredicate", () => {
  it("renders every real precondition without throwing or falling back to JSON", () => {
    for (const t of content.templates) {
      for (const p of t.preconditions) {
        expect(() => renderPredicate(p)).not.toThrow();
        expect(renderPredicate(p).startsWith("unknown predicate")).toBe(false);
      }
    }
  });

  it("renders a cmp predicate in short words", () => {
    expect(renderPredicate({ cmp: { role: "shop", path: "compliance", op: "lt", value: 400 } })).toBe("shop.compliance < 400");
  });

  it("renders decided, not, and playerControlled", () => {
    expect(renderPredicate({ decided: { optionId: "accept" } })).toContain("accept");
    expect(renderPredicate({ not: { decided: { optionId: "accept" } } })).toMatch(/^not \(/);
    expect(renderPredicate({ playerControlled: { role: "me", is: true } })).toBe("me is player-controlled");
    expect(renderPredicate({ playerControlled: { role: "me", is: false } })).toBe("me is not player-controlled");
  });

  it("falls back to JSON for a shape it does not recognize", () => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any -- deliberately malformed, to exercise the fallback
    expect(renderPredicate({ neverHeardOfIt: true } as any)).toContain("unknown predicate");
  });
});

describe("renderEffect", () => {
  it("renders every real effect without throwing or falling back to JSON", () => {
    for (const t of content.templates) {
      const allEffectLists = [
        ...(t.decision?.options.map((o) => o.effects) ?? []),
        ...t.resolve.map((o) => o.effects),
      ];
      for (const effects of allEffectLists) {
        for (const e of effects) {
          expect(() => renderEffect(e)).not.toThrow();
          expect(renderEffect(e).startsWith("unknown effect")).toBe(false);
        }
      }
    }
  });

  it("renders a FavorDelta in words", () => {
    expect(renderEffect({ fact: "FavorDelta", from: "$sponsor", to: "$me", delta: -15, cause: { rule: "x" } })).toBe("FavorDelta sponsor→me -15");
  });

  it("renders a MoneyMint in words", () => {
    expect(renderEffect({ fact: "MoneyMint", to: "$me.account", amount: 55, money: "dirty", source: "cardGame", cause: { rule: "x" } })).toBe(
      "MoneyMint me +55 dirty (cardGame)",
    );
  });

  it("renders a schedule effect with its probability as a percentage", () => {
    expect(renderEffect({ schedule: { templateId: "assoc.sponsor.repay", delay: 6, probability: 6000 } })).toBe(
      "schedule assoc.sponsor.repay in 6 (60%)",
    );
  });
});

describe("outcomesForOption", () => {
  const resolve = [
    { id: "a", when: [{ decided: { optionId: "x" } }], effects: [] },
    { id: "b", when: [{ decided: { optionId: "y" } }], effects: [] },
  ];

  it("returns only the outcomes gated to the given option", () => {
    expect(outcomesForOption(resolve, "x").map((o) => o.id)).toEqual(["a"]);
  });

  it("returns every outcome when none of them are gated by `decided`", () => {
    const ungated = [{ id: "a", effects: [] }, { id: "b", effects: [] }];
    expect(outcomesForOption(ungated, "whatever").map((o) => o.id)).toEqual(["a", "b"]);
  });

  it("returns no outcomes for an option nothing is gated to, when others are", () => {
    expect(outcomesForOption(resolve, "z")).toEqual([]);
  });
});
